#!/sbin/openrc-run
### BEGIN INIT INFO
# Provides: hildon-control-panel-personalisation
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Hildon Control Panel Personalisation
### END INIT INFO

start() {
    ebegin "Starting hildon-control-panel-personalisation"
	if [ ! -e /etc/hildon/theme/index.theme ]; then
        ebegin "Setting default theme"
        /usr/bin/personalisation /usr/share/themes/alpha;
	fi
}
